out_dir_name = "<CONF_FILE_NAME>"
suffix = false
batch_size_eval = 256

[data]
path = "~/dataset/traffic/traffic.csv"
colname_timestamp = "date"
white_list = [0, 1, 2]
seq_len = [24, 7, 4]
pred_len = [24, 7]

# -------------------- models --------------------

[[models]]
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [24, 7, 4]
pred_len = [24, 7]
period_len = [24, 7]
[models.report]
name = "SimpleAve"

[[models]]
path = "shiroinu.models.patchtst.PatchTSTIqr"
[models.params]
seq_len = [24, 7, 4]
pred_len = [24, 7]

# -------------------- task templates --------------------

[[task_templates]]
reset_model = true
[task_templates.criterion_target]
path = "shiroinu.criteria.MSELoss"
params = {}
[task_templates.batch_sampler]
path = "shiroinu.batch_sampler.BatchSamplerShuffle"
params = { batch_size = 64 }
[task_templates.optimizer]
path = "torch.optim.Adam"
params = { lr = 0.001 }
[task_templates.lr_scheduler]
path = "torch.optim.lr_scheduler.CosineAnnealingLR"
params = { T_max = 10 }
# path = "torch.optim.lr_scheduler.CosineAnnealingWarmRestarts"
# params = { T_0 = 10 }

# -------------------- tasks --------------------

[[tasks]]  # 0
task_type = "train"
model = { id = 1, state_path = "" }
task_template_id = 0
n_epoch = 5
n_epoch_ref = -1
early_stop = true
train_range = [0.0, 0.3]
valid_range = [0.3, 0.4]

[[tasks]]  # 1
task_type = "train"
model = { id = 1, state_path = "" }
task_template_id = 0
n_epoch = -1
n_epoch_ref = 0
early_stop = false
train_range = [0.0, 0.4]
[tasks.report]
note = "no decay"

[[tasks]]  # 2
task_type = "eval"
valid_range = [0.4, 0.5]
models = [
{ id = 0, state_path = "" },
{ id = 1, state_path = "<HERE>model_task_1_end.pth" },
]
percentile_points = [0.05, 0.25, 0.5, 0.75, 0.95]
[tasks.criterion_eval]
path = "shiroinu.criteria.MAELoss"
params = {}
