out_dir_name = "<CONF_FILE_NAME>"
suffix = false
batch_size_eval = 256

[data]
path = "~/dataset/traffic/traffic.csv"
colname_timestamp = "date"
seq_len = [24, 7, 4]
pred_len = [24, 7]

# -------------------- models --------------------

[[models]]  # 0
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [24, 7, 4]
pred_len = [24, 7]
period_len = [24, 7]
[models.report]
name = "SimpleAve"

[[models]]  # 1
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [24, 7, 4]
pred_len = [24, 7]
period_len = [24, 7]
decay_rate = 0.9
[models.report]
name = "SimpleAve09"

[[models]]  # 2
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [24, 7, 4]
pred_len = [24, 7]
period_len = [24, 7]
decay_rate = 0.8
[models.report]
name = "SimpleAve08"

[[models]]  # 3
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [24, 7, 4]
pred_len = [24, 7]
period_len = [24, 7]
decay_rate = 0.7
[models.report]
name = "SimpleAve07"

[[models]]  # 4
path = "shiroinu.models.simple_average.SimpleAverage"
[models.params]
seq_len = [24, 7, 4]
pred_len = [24, 7]
period_len = [24, 7]
decay_rate = 0.6
[models.report]
name = "SimpleAve06"

[[models]]  # 5
path = "shiroinu.models.simple_average.SimpleAverageTrainable"
[models.params]
seq_len = [24, 7, 4]
pred_len = [24, 7]
period_len = [24, 7]
n_channel = 862
[models.report]
name = "SimpleAveT"

# -------------------- task templates --------------------

[[task_templates]]
reset_model = true
[task_templates.batch_sampler]
path = "shiroinu.batch_sampler.BatchSamplerShuffle"
params = { batch_size = 64 }
[task_templates.optimizer]
path = "torch.optim.Adam"
params = { lr = 0.001 }
[task_templates.lr_scheduler]
path = "torch.optim.lr_scheduler.CosineAnnealingLR"
params = { T_max = 10 }

# -------------------- tasks --------------------

[[tasks]]  # 0
task_type = "train"
model = { id = 5, state_path = "" }
task_template_id = 0
n_epoch = 40
n_epoch_ref = -1
early_stop = true
train_range = [0.0, 0.6]
valid_range = [0.6, 0.8]
[tasks.criterion_target]
path = "shiroinu.criteria.MSELoss"
params = {}

[[tasks]]  # 1
task_type = "train"
model = { id = 5, state_path = "" }
task_template_id = 0
n_epoch = -1
n_epoch_ref = 0
early_stop = false
train_range = [0.0, 0.8]
[tasks.criterion_target]
path = "shiroinu.criteria.MSELoss"
params = {}

[[tasks]]  # 2
task_type = "eval"
valid_range = [0.8, 1.0]
models = [
{ id = 0, state_path = "" },
{ id = 1, state_path = "" },
{ id = 2, state_path = "" },
{ id = 3, state_path = "" },
{ id = 4, state_path = "" },
{ id = 5, state_path = "<HERE>model_task_1_end.pth" },
]
percentile_points = [0.05, 0.25, 0.5, 0.75, 0.95]
[tasks.criterion_eval]
path = "shiroinu.criteria.MAELoss"
params = {}
